export const ERROR_CODES = [
  "INVALID_TRANSITION",
  "JOIN_CLOSED",
  "SWITCH_LOCKED",
  "NOT_ELIGIBLE",
  "RATE_LIMITED",
  "UNAUTHORIZED",
  "UNKNOWN_PLAYER",
  "EXTEND_REJECTED",
  "VALIDATION",
  "SESSION_REPLACED",
  "GAME_NOT_FOUND",
  "BALANCE_INCOMPLETE",
  "CONFIRMATION_REQUIRED",
  "EMPTY_ROSTER",
  "CONCURRENT_MODIFICATION",
  "INVALID_WILDCARD",
  "MOVE_NOT_ALLOWED",
  "MOVE_WOULD_OVERSHOOT",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
